/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.4 cake.gltf --transform
Author: Citrus (https://sketchfab.com/citrusfriendd)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cake-bd2b824c98b34bd2a09462524452492c
Title: Cake
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/cake-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.pCylinder1_lambert2_0.geometry}
        material={materials.lambert2}
      />
    </group>
  );
}

useGLTF.preload("/cake-transformed.glb");
