/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.4 cake.gltf --transform
Author: adsky_pes (https://sketchfab.com/adsky_pes)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sweet-cake-00ce143127e44b7e80df1488be2799f9
Title: Sweet cake
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/cake-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Plane016_cake_0.geometry}
        material={materials.cake}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/cake-transformed.glb");
