/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.4 cake.gltf --transform
Author: neos_nelia (https://sketchfab.com/neosnelia)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cake-0fda1c7d832a4a8f8361ff40829ba239
Title: cake
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/cake-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Cube016_Material009_0.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Cube015_Material008_0.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Plane002_Material010_0.geometry}
        material={materials.PaletteMaterial001}
        position={[10.866, 42.645, -12.959]}
        rotation={[-1.364, 0.04, 1.931]}
        scale={[2.405, 2.398, 2.404]}
      />
    </group>
  );
}

useGLTF.preload("/cake-transformed.glb");
