/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.4 cake.gltf --transform
Author: Johana-PS (https://sketchfab.com/Johana-PS)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cake-3d-756da5ef6d0249479510e6bdd1856e42
Title: Cake 3D
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/cake-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_1.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Object_11.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials.PaletteMaterial001}
        position={[-0.757, 1.215, 1.499]}
        rotation={[-0.015, 1.571, 0]}
        scale={1.728}
      />
    </group>
  );
}

useGLTF.preload("/cake-transformed.glb");
