/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.4 cake.gltf --transform
Author: Strawbie (https://sketchfab.com/strawbie133)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/strawberry-cake-0b5e74462cac4869b6cfb64c325b6d89
Title: Strawberry Cake
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/cake-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.pCube99_red_strawberry_0.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.pCylinder70_cream_0.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.sweep9_pinker_icing_0.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.pCube115_red_strawberry_0.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.pCone1_orange_fire_0.geometry}
        material={materials.PaletteMaterial002}
      />
      <mesh
        geometry={nodes.pCylinder67_pink_icing_0.geometry}
        material={materials.PaletteMaterial001}
        position={[0, 0.01, 0]}
        scale={[0.03, 0.01, 0.03]}
      />
    </group>
  );
}

useGLTF.preload("/cake-transformed.glb");
