/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.4 icecream.gltf --transformam.gl
Author: AtandMi (https://sketchfab.com/AtandMi)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/icecream-9ab7bd74b12d44d1928c6b0b08a92b85
Title: icecream
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/icecream.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 1.202, 0]} rotation={[0.063, 0, 0]} scale={0.082}>
            <mesh geometry={nodes.Object_6.geometry} material={materials.coon2} />
            <mesh geometry={nodes.Object_7.geometry} material={materials.coon2} />
          </group>
          <mesh geometry={nodes.Object_4.geometry} material={materials.ice4} position={[0, 1.202, 0]} rotation={[0.063, 0, 0]} scale={0.082} />
          <mesh geometry={nodes.Object_9.geometry} material={materials.kami1} position={[0, 1.202, 0]} rotation={[0.063, 0, 0]} scale={0.082} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/icecream.gltf')
